### ISSUE TITLE
Add official logos

### ISSUE THREAD

**Issue by lreimer** [seu-as-code/seu-as-code.github.io#12]
Add the offical designed logos on the site.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.github.io/12/af53565c-9471-4f73-accd-8e99faa187ed/2b9b26a5-968c-4a6f-9385-800b63f433a1) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by lreimer** [comment]
Closed via #16. Thanks @RaphaelSanches
