### ISSUE TITLE
Add 15 minutes showcase video

### ISSUE THREAD

**Issue by lreimer** [seu-as-code/seu-as-code.github.io#13]
Add the Youtube Video from the Gradle Summit 2016.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.github.io/13/af53565c-9471-4f73-accd-8e99faa187ed/dc622722-24ce-4deb-8a92-c3b474f21c89) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by lreimer** [comment]
https://youtu.be/9Pb9Df1o0rY?list=PLLQbIfXVLZqECVFyUGPwxvsXmX390FQTN
